language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "rake spec"
rvm:
  - 2.2.4
  - 2.3.0
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - ruby-head
matrix:
  include:
    - rvm: jruby-9.0.5.0
      env:
        - "JRUBY_OPTS='--dev -J-Xmx1024M'"
  allow_failures:
    - rvm: ruby-head
